# Generated by BoostInstall.cmake for boost_decimal-1.92.0

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "Found boost_decimal ${boost_decimal_VERSION} at ${boost_decimal_DIR}")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_decimal-targets.cmake")
